## login
POST http://localhost:5000/api/v0/login
content-type: application/json

{
  "username":"doc_oc",
  "password":"MTIz"
}

# {
#   "message": "Success",
#   "data": {
#     "username": "doc_oc",
#     "role": "doctor",
#     "info": {
#       "username": "doc_oc",
#       "name": "Doctor Octavious",
#       "specialization": "Neuroscience",
#       "degree": "MBBS",
#       "phone": "01798543234",
#       "email": "dococ@gmail.com"
#     }
#   }
# }
