POST http://localhost:5000/api/v0/get_prescribed_drug_by_drug_id/
content-type: application/json

{
    "prescription_id": 2,
    "drug_id": 4
}

# {
#   "message": "Success",
#   "data": {
#     "prescriptionId": 2,
#     "drugId": 4,
#     "prescribedDosage": "1+1+1, 7 days a week",
#     "brandName": "Zestril:10mg",
#     "genericName": "Lisinopril",
#     "prescriptionDate": "2023-08-17T00:00:00.000Z"
#   }
# }