post http://localhost:5000/api/v0/add_medical_history
content-type: application/json

[
    {
        "disease_id": 4,
        "patient_id": 1,
        "date": "2020-01-01",
        "prescription": "paracetamol"
    },
    {
        "disease_id": 5,
        "patient_id": 1,
        "date": "2020-05-15",
        "prescription": null
    }
]

# {
#   "message": "Success",
#   "data": {
#     "disease_id": 5,
#     "date": "2020-05-15T00:00:00.000Z",
#     "patient_id": 1,
#     "prescription": null
#   }
# }