## login
POST http://localhost:5000/api/v0/create_practice
content-type: application/json

{
    "name": "practice1"
}

# {
#   "message": "Success",
#   "data": {
#     "id": 5,
#     "name": "practice1"
#   }
# }