## login
POST http://localhost:5000/api/v0/search_patient/
content-type: application/json

{
    "phone":"1234567890"
}

# {
#   "message": "Success",
#   "data": [
#     {
#       "id": 1,
#       "name": "John Doe",
#       "phone": "1234567890",
#       "nid": "ABCD1234",
#       "dob": "1993-05-15T00:00:00.000Z",
#       "gender": "M",
#       "addresses": [
#         "Elk Street 1",
#         "Elm Street 2"
#       ],
#       "address_from": [
#         "2020-01-01T00:00:00.000Z",
#         "2022-03-15T00:00:00.000Z"
#       ],
#       "address_to": [
#         "2022-03-15T00:00:00.000Z"
#       ],
#       "occupations": [
#         "Software Engineer",
#         "Project Manager"
#       ],
#       "occupation_from": [
#         "2020-01-01T00:00:00.000Z",
#         "2022-03-15T00:00:00.000Z"
#       ],
#       "occupation_to": [
#         "2022-03-16T00:00:00.000Z"
#       ],
#       "height": 175.5,
#       "weight": 70.5
#     }
#   ]
# }