## Update Patient. Deprecated. Use update_patient_test and med_history 
PUT http://localhost:5000/api/v0/update_new_patient
content-type: application/json

{
  "basic_info":
  {
    "id"  : 21,
    "height": 175,
    "weight": 70,
    "addresses": [
      "Address 4",
      "Address 5",
      "Address 6"
    ],
    "address_from": [
      "2023-04-01T00:00:00.000Z",
      "2023-05-01T00:00:00.000Z",
      "2023-06-01T00:00:00.000Z"
    ],
    "address_to": [
      "2023-04-15T00:00:00.000Z",
      "2023-05-31T00:00:00.000Z"
    ],
    "occupations": ["Occupation A", "Occupation B"],
    "occupation_from": ["2022-01-01T00:00:00Z", "2022-02-01T00:00:00Z"],
    "occupation_to": ["2022-12-31T00:00:00Z", "2022-12-31T00:00:00Z"],
    "travel_history": ["Place X", "Place Y"],
    "travel_from": ["2021-01-01T00:00:00Z", "2021-02-01T00:00:00Z"],
    "travel_to": ["2021-01-15T00:00:00Z", "2021-02-15T00:00:00Z"]
  },
  "medical_history" : [
    {
        "disease_id": 4,
        "patient_id": 21,
        "date": "2020-01-01",
        "prescription": "paracetamol"
    },
    {
        "disease_id": 5,
        "patient_id": 21,
        "date": "2020-05-15",
        "prescription": null
    }
  ]
}

# {
#   "message": "Successfully updated",
#   "data": {
#     "id": 17,
#     "name": "John Smith",
#     "phone": "0987654321",
#     "nid": "987654321",
#     "dob": "1995-05-15T00:00:00.000Z",
#     "gender": "F",
#     "hometown": "Hometown B",
#     "addresses": [
#       "Address 4",
#       "Address 5",
#       "Address 6"
#     ],
#     "address_from": [
#       "2023-04-01T00:00:00.000Z",
#       "2023-05-01T00:00:00.000Z",
#       "2023-06-01T00:00:00.000Z"
#     ],
#     "address_to": [
#       "2023-04-15T00:00:00.000Z",
#       "2023-05-31T00:00:00.000Z"
#     ],
#     "occupations": [
#       "Occupation A",
#       "Occupation B"
#     ],
#     "occupation_from": [
#       "2022-01-01T00:00:00.000Z",
#       "2022-02-01T00:00:00.000Z"
#     ],
#     "occupation_to": [
#       "2022-12-31T00:00:00.000Z",
#       "2022-12-31T00:00:00.000Z"
#     ],
#     "travel_history": [
#       "Place X",
#       "Place Y"
#     ],
#     "travel_from": [
#       "2021-01-01T00:00:00.000Z",
#       "2021-02-01T00:00:00.000Z"
#     ],
#     "travel_to": [
#       "2021-01-15T00:00:00.000Z",
#       "2021-02-15T00:00:00.000Z"
#     ],
#     "height": 175,
#     "weight": 70
#   }
# }